= Using Adoc in Bespoke
Aitor Corchero
:organization: ; Eurecat Technology Centre
:hide-uri-scheme:

[#install]
[backdrop-role="installation"]
== Adoc Installation in Bespoke

[backdrop-role="installation"]
== Add dependencies to package.json
[source,json]
----
"gulp-chmod": "^1.3.0",
"gulp-exec": "^2.1.2",
----

[backdrop-role="installation"]
== Install dependencies in the project (shell)
[source,shell]
----
npm i
----

[backdrop-role="installation"]
== Prepare tasks in the gulpfile.js 
- Define the variables to use
[source,javascript]
----
chmod = require('gulp-chmod'),
exec = require('gulp-exec'),
----

[backdrop-role="installation"]
== Prepare tasks in the gulpfile.js 
Define the task in charge of converting adoc to html

[source,javascript]
----
gulp.task('html', ['clean:html'], function() {
 return gulp.src('src/index.adoc')
  .pipe(isDist ? through() : plumber())
  .pipe(exec('bundle exec asciidoctor-bespoke 
  -D public -T src/templates -o - src/index.adoc', 
  { pipeStdout: true }))
  .pipe(exec.reporter({ stdout: false }))
  .pipe(rename('index.html'))
  .pipe(gulp.dest('dist'))
  .pipe(chmod(644))
  .pipe(gulp.dest('public'))
  .pipe(connect.reload());
});
----

[backdrop-role="installation"]
== Prepare tasks in the gulpfile.js 
Define the whach function

Replace: 

[source,javascript]
----
 gulp.watch('src/**/*.jade', ['html']);
----

By: 

[source,javascript]
----
 gulp.watch('src/**/*.adoc', ['html']);
----


== ¿What can We do with bespoke?

== Enable key interaction

Powered by https://github.com/markdalgleish/bespoke-keys

== Touch Interaction 

Powered by https://github.com/bespokejs/bespoke-touch

== Bullet List
bullet Powered by https://github.com/markdalgleish/bespoke-bullets">bespoke-bullets

- Bullet 1
- Bullet 2
- Bullet 3

== Responsive Slides
Powered by https://github.com/markdalgleish/bespoke-scale

== Syntax Highlighting
Powered by Lea Verou's https://github.com/LeaVerou/prism

[source,javascript]
----
code.language-javascript. bespoke.from('article', [
  classes(),
  keys(),
  touch(),
  bullets('li, .bullet')
]);
----

[backdrop-role="emphatic"]
== Emphatic Slide 
Powered by https://github.com/markdalgleish/bespoke-backdrop

== Playing with tables

[cols="40,60", options="header"] 
|===
|Header 1
|Header 2

| Row 1
| Row 2

|===

== Put Hands on the asciidoc

- Edit the asciidoc in src/index.adoc
- Edit the styles at src/styles/main.styl
- Enjoy Playing!!!